### ISSUE TITLE
Unable to login to UI with chart default values

### ISSUE THREAD

**Issue by krzwiatrzyk-lgd** [mergestat/helm-charts#95]
I have installed a MergeStat with default values and port-forwarded an UI with 3000 port. Trying to log in via `postgres:password` results with `Incorrect password` message.

Moreover, `/` should redirect me to `/login` if I am unauthenticated, this doesn't occur - I know this should be opened as Issue in another repo.

**Comment by patrickdevivo** [comment]
@krzwiatrzyk-lgd sorry about that! we're pretty sure the issue you encountered is resolved by this fix: https://github.com/mergestat/helm-charts/pull/113

**Comment by patrickdevivo** [comment]
Closing this out as that was just merged! If your problem persists - please reopen! Thanks
